[build]
  command = "yarn deploy"
  publish = "out"

  [build.environment]
  # Environment variables are set here
  NODE_VERSION = "18.20.4"

[[plugins]]
  package = "netlify-plugin-onboarding"

[template.environment]
  NEXT_PUBLIC_CHEC_PUBLIC_KEY = "Chec Public Key (under Setup > Developer)"
